### ISSUE TITLE
Support YAML

### ISSUE THREAD

**Issue by muuvmuuv** [Unibeautify/beautifier-prettier#130]
Prettier supports YAML, see https://prettier.io/docs/en/language-support.html

Create prettier option for YAML here: https://github.com/Unibeautify/beautifier-prettier/blob/master/src/options.ts
Adding it YAML to the beautifier here: https://github.com/Unibeautify/beautifier-prettier/blob/master/src/index.ts#L35-L47

> I do not really know which option prettier YAML supports, so I think it's try and error?

**Comment by Glavin001** [comment]
Sounds great! Pull requests welcome 😃

**Comment by muuvmuuv** [comment]
Options can be found here: https://github.com/prettier/prettier/blob/master/src/language-yaml/options.js

**Comment by muuvmuuv** [comment]
@Glavin001 I'll work on this.
